from datetime import date, datetime, time, timezone
from pathlib import Path
from uuid import uuid4
from sqlalchemy import select
from sqlalchemy.orm import Session
from app.core.config import get_settings
from app.db.models import AuditSession, Comment, Finding, GeneratedReport, RemediationAction

def create_afr(db: Session, audit_session_id: int, user_id: int, fmt: str,
               practice_area_codes: list[str] | None = None,
               severities: list[str] | None = None,
               statuses: list[str] | None = None,
               from_date: date | None = None, to_date: date | None = None) -> GeneratedReport:
    """Create an AFR from one persisted audit session and optional finding filters."""
    audit = db.get(AuditSession, audit_session_id)
    if not audit: raise ValueError('Audit session not found')
    audit_context = {
        'name': audit.audit_name or f'Audit session #{audit_session_id}',
        'date': audit.audit_date.isoformat() if audit.audit_date else '',
        'auditors': audit.auditors or '',
        'auditees': audit.auditees or '',
    }
    query = select(Finding).where(Finding.audit_session_id == audit_session_id)
    if practice_area_codes: query = query.where(Finding.practice_area_code.in_(practice_area_codes))
    if severities: query = query.where(Finding.severity.in_(severities))
    if statuses: query = query.where(Finding.status.in_(statuses))
    if from_date: query = query.where(Finding.created_at >= datetime.combine(from_date, time.min, tzinfo=timezone.utc))
    if to_date: query = query.where(Finding.created_at <= datetime.combine(to_date, time.max, tzinfo=timezone.utc))
    findings = db.scalars(query.order_by(Finding.severity, Finding.practice_area_code, Finding.id)).all()
    finding_ids = [finding.id for finding in findings]
    comments = {finding_id: [] for finding_id in finding_ids}
    actions = {finding_id: [] for finding_id in finding_ids}
    if finding_ids:
        for finding_id, body in db.execute(
            select(Comment.finding_id, Comment.body)
            .where(Comment.finding_id.in_(finding_ids))
            .order_by(Comment.finding_id, Comment.created_at)
        ):
            comments[finding_id].append(body)
        for finding_id, status, action in db.execute(
            select(RemediationAction.finding_id, RemediationAction.status, RemediationAction.action)
            .where(RemediationAction.finding_id.in_(finding_ids))
            .order_by(RemediationAction.finding_id, RemediationAction.created_at)
        ):
            actions[finding_id].append(f'{status}: {action}')
    created = datetime.now(timezone.utc)
    output = get_settings().output_dir / f'AFR_session-{audit_session_id}_{created:%Y%m%dT%H%M%SZ}_{uuid4().hex[:8]}.{fmt}'
    if fmt == 'xlsx':
        from openpyxl import Workbook
        wb=Workbook(); ws=wb.active; ws.title='Detailed Findings'; ws.append(['Finding ID','Rule ID','Practice Area','Severity','Finding','Description','Recommendation','Status','Comments','Remediation actions'])
        for f in findings: ws.append([f.id,f.rule_id,f.practice_area_code,f.severity,f.title,f.description,f.recommendation,f.status,'\n'.join(comments[f.id]),'\n'.join(actions[f.id])])
        meta=wb.create_sheet('Report Metadata'); meta.append(['Audit Session',audit_session_id]); meta.append(['Audit name',audit_context['name']]); meta.append(['Audit date',audit_context['date']]); meta.append(['Auditors',audit_context['auditors']]); meta.append(['Auditees',audit_context['auditees']]); meta.append(['Generated At',created.isoformat()]); meta.append(['Generated By',user_id]); meta.append(['Practice areas', ', '.join(practice_area_codes or []) or 'All']); meta.append(['Severities', ', '.join(severities or []) or 'All']); meta.append(['Statuses', ', '.join(statuses or []) or 'All']); meta.append(['From date', from_date.isoformat() if from_date else '']); meta.append(['To date', to_date.isoformat() if to_date else '']); wb.save(output)
    elif fmt == 'docx':
        from docx import Document
        doc=Document(); doc.add_heading('CMMI Audit Findings Report (AFR)',0); doc.add_paragraph(f"Audit: {audit_context['name']} | Session: {audit_session_id} | Date: {audit_context['date'] or 'Not recorded'} | Auditors: {audit_context['auditors'] or 'Not recorded'} | Auditees: {audit_context['auditees'] or 'Not recorded'} | Generated: {created.isoformat()} | Creator: {user_id}")
        table=doc.add_table(rows=1, cols=4); table.style='Table Grid'
        for cell,value in zip(table.rows[0].cells,['Rule','PA','Severity','Finding']): cell.text=value
        for f in findings:
            cells=table.add_row().cells
            for cell,value in zip(cells,[f.rule_id or '',f.practice_area_code,f.severity,f.title]): cell.text=str(value)
            doc.add_paragraph(f'Recommendation: {f.recommendation}')
            if comments[f.id]: doc.add_paragraph(f'Comments: {" | ".join(comments[f.id])}')
            if actions[f.id]: doc.add_paragraph(f'Remediation: {" | ".join(actions[f.id])}')
        doc.save(output)
    else:
        from reportlab.lib.pagesizes import A4
        from reportlab.pdfgen import canvas
        pdf=canvas.Canvas(str(output), pagesize=A4); y=800; pdf.setFont('Helvetica-Bold',16); pdf.drawString(48,y,'CMMI Audit Findings Report (AFR)'); y-=26; pdf.setFont('Helvetica',8)
        pdf.drawString(48,y,f"Audit: {audit_context['name']} | session {audit_session_id} | date: {audit_context['date'] or 'Not recorded'}"); y-=12
        pdf.drawString(48,y,f"Auditors: {audit_context['auditors'] or 'Not recorded'} | Auditees: {audit_context['auditees'] or 'Not recorded'}"); y-=12
        pdf.drawString(48,y,f'Generated {created.isoformat()} by {user_id}'); y-=12
        for f in findings:
            line=f'[{f.severity.upper()}] {f.practice_area_code} {f.rule_id or ""}: {f.title}'
            for segment in [line[i:i+105] for i in range(0,len(line),105)]:
                if y<50: pdf.showPage(); y=800
                pdf.drawString(48,y,segment); y-=12
        pdf.save()
    report=GeneratedReport(audit_session_id=audit_session_id,report_type=f'afr_{fmt}',storage_path=str(output),created_by_id=user_id); db.add(report); db.commit(); db.refresh(report); return report
