// ─── One-time Excel → JS data module converter ─────────────────────────────
//
// Reads the reference checklist workbook and regenerates:
//   src/ruleChecklist.js       (MASTER sheet  -> RULE_CHECKLIST)
//   src/documentTypeConfig.js (Sheet5        -> DOCUMENT_TYPE_CONFIG)
//   src/sheet2Data.js          (Sheet2        -> SHEET2_DATA)
//
// Re-run with: node scripts/buildRuleChecklist.mjs
// (whenever the source .xlsx changes — the generated files are not meant
// to be hand-edited, same convention as src/cmmiKB.js)

import { fileURLToPath } from 'node:url'
import path from 'node:path'
import fs from 'node:fs'
import XLSX from 'xlsx'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const WORKBOOK_PATH = path.join(ROOT, 'rule checklist', 'CMMI_v3_Rule_Based_Audit_Checklist_v2.xlsx')

const wb = XLSX.readFile(WORKBOOK_PATH)

function sheetRows(sheetName) {
  const ws = wb.Sheets[sheetName]
  if (!ws) throw new Error(`Sheet not found in workbook: ${sheetName}`)
  return XLSX.utils.sheet_to_json(ws, { header: 1, defval: '' })
}

function cell(row, i) {
  return String(row[i] ?? '').trim()
}

function writeModule(relPath, exportName, data, sourceSheet) {
  const banner =
    `// AUTO-GENERATED by scripts/buildRuleChecklist.mjs from\n` +
    `// "rule checklist/CMMI_v3_Rule_Based_Audit_Checklist_v2.xlsx" (sheet: ${sourceSheet}).\n` +
    `// Do not edit manually — re-run the script to regenerate.\n\n`
  const body = `export const ${exportName} = ${JSON.stringify(data, null, 2)};\n`
  fs.writeFileSync(path.join(ROOT, relPath), banner + body)
}

// ─── FILE 1: src/ruleChecklist.js (MASTER sheet) ───────────────────────────

function buildRuleChecklist() {
  const rows = sheetRows('MASTER')
  const rules = []

  for (const row of rows) {
    const level = cell(row, 1)
    const ruleId = cell(row, 2)
    const auditCheck = cell(row, 4)
    const gapText = cell(row, 6)

    if (!ruleId || ruleId === 'Rule ID') continue // title/header/domain-header/blank rows
    if (level === 'L2-Block') continue // block-intro rows carry no Rule ID anyway, kept as an explicit guard

    const prefixMatch = ruleId.match(/^([A-Za-z]+)-/)
    const practiceArea = prefixMatch ? prefixMatch[1] : ruleId

    rules.push({
      ruleId,
      practiceArea,
      level,
      isGate: level.includes('Gate'),
      isCheck: level.includes('Check'),
      isProbe: level.includes('Probe'),
      auditCheck,
      gapText,
    })
  }

  return rules
}

// ─── FILE 2: src/documentTypeConfig.js (Sheet5) ────────────────────────────

function buildDocumentTypeConfig() {
  const rows = sheetRows('Sheet5')
  const entries = []

  for (const row of rows) {
    const documentType = cell(row, 1)
    if (!documentType || documentType === 'Document / Evidence') continue // blank / header row

    const practiceAreas = cell(row, 2).split(/[/,]/).map(s => s.trim()).filter(Boolean)
    // Column E mixes comma AND semicolon as separators (e.g. "risk category;
    // risk appetite; probability scale; impact scale" nested inside a
    // comma-separated list) — splitting on comma alone left semicolon-joined
    // phrases as one long keyword instead of several short ones.
    const keywords = cell(row, 4).split(/[,;]/).map(s => s.trim()).filter(Boolean)
    const expectedEvidence = cell(row, 5)

    entries.push({ documentType, practiceAreas, keywords, expectedEvidence })
  }

  return entries
}

// ─── FILE 3: src/sheet2Data.js (Sheet2) ────────────────────────────────────
//
// Domain Name / Practice Area Name are Excel-merged cells that only carry a
// value on the first row of each group (subsequent rows read back as blank
// via sheet_to_json) — forward-filled from the last seen value, keyed off
// Related Document Name being present (the real per-row identifier).

function buildSheet2Data() {
  const rows = sheetRows('Sheet2')
  const entries = []
  let lastDomain = ''
  let lastPracticeArea = ''

  for (const row of rows) {
    const domainRaw = cell(row, 1)
    const paRaw = cell(row, 2)
    const relatedDocument = cell(row, 3)

    if (domainRaw && domainRaw !== 'Domain Name') lastDomain = domainRaw
    if (paRaw && paRaw !== 'Practice Area Name') lastPracticeArea = paRaw

    if (!relatedDocument || relatedDocument === 'Related Document Name') continue // blank / header row

    const keywords = cell(row, 4).split(/[,;]/).map(s => s.trim()).filter(Boolean)
    const exampleEvidence = cell(row, 5)

    entries.push({
      domain: lastDomain,
      practiceArea: lastPracticeArea,
      relatedDocument,
      keywords,
      exampleEvidence,
    })
  }

  return entries
}

// ─── Run ────────────────────────────────────────────────────────────────

const ruleChecklist = buildRuleChecklist()
const documentTypeConfig = buildDocumentTypeConfig()
const sheet2Data = buildSheet2Data()

writeModule('src/ruleChecklist.js', 'RULE_CHECKLIST', ruleChecklist, 'MASTER')
writeModule('src/documentTypeConfig.js', 'DOCUMENT_TYPE_CONFIG', documentTypeConfig, 'Sheet5')
writeModule('src/sheet2Data.js', 'SHEET2_DATA', sheet2Data, 'Sheet2')

console.log(`RULE_CHECKLIST: ${ruleChecklist.length} rules written to src/ruleChecklist.js`)
console.log(`DOCUMENT_TYPE_CONFIG: ${documentTypeConfig.length} document types written to src/documentTypeConfig.js`)
console.log(`SHEET2_DATA: ${sheet2Data.length} entries written to src/sheet2Data.js`)
