// AUTO-GENERATED by scripts/buildRuleChecklist.mjs from
// "rule checklist/CMMI_v3_Rule_Based_Audit_Checklist_v2.xlsx" (sheet: Sheet5).
// Do not edit manually — re-run the script to regenerate.
//
// MANUALLY PATCHED (post-generation): several `practiceAreas` values in the
// source spreadsheet use codes that do not exist in RULE_CHECKLIST (the
// MASTER sheet) — "Project Management", "Estimation", "MC", "VER", "VAL",
// "SAM", "PPL" — so evidenceValidationEngine.js's `RULE_CHECKLIST.filter(rule
// => practiceAreas.includes(rule.practiceArea))` would silently find zero
// rules for any document classified under one of those codes. Each has been
// remapped to its closest real RULE_CHECKLIST code (content-verified against
// RULE_CHECKLIST's own auditCheck text, not just a name guess):
//   "Project Management" -> PLAN  (redundant with the PLAN already present)
//   "Estimation"          -> EST  (RULE_CHECKLIST's Estimating code)
//   "MC" (Monitor&Control) -> MPM (RULE_CHECKLIST has no MC; MPM's rules are
//                                  literally planned-vs-actual/performance
//                                  tracking, the same content MC covers here)
//   "VER" / "VAL"          -> VV  (RULE_CHECKLIST combines Verification and
//                                  Validation into one "VV" code, never split)
//   "SAM"                  -> SUP (RULE_CHECKLIST's Supplier code; SUP-G1
//                                  literally reads "Locate the Supplier or
//                                  Vendor Agreement")
//   "PPL" (People/Training) -> OT (RULE_CHECKLIST's Organisational Training
//                                  code; "training" keyword hits concentrate
//                                  8:1 in OT over every other code)
// Re-running scripts/buildRuleChecklist.mjs will regenerate this file from
// the untouched source spreadsheet and REVERT this patch — until the
// spreadsheet's Sheet5 PA column is corrected at the source, re-apply this
// same mapping after any regeneration.

export const DOCUMENT_TYPE_CONFIG = [
  {
    "documentType": "Project Charter / Initiation Document",
    "practiceAreas": [
      "PLAN"
    ],
    "keywords": [
      "Scope",
      "objectives",
      "stakeholders",
      "dates",
      "deliverables",
      "approvals"
    ],
    "expectedEvidence": "Approved charter; stakeholder details; scope baseline"
  },
  {
    "documentType": "SOW / Contract / Agreement/RFP(request for proposal)",
    "practiceAreas": [
      "PLAN",
      "RDM"
    ],
    "keywords": [
      "Scope of work",
      "deliverables",
      "milestones",
      "responsibilities",
      "acceptance criteria",
      "SLAs"
    ],
    "expectedEvidence": "Signed SOW/contract and amendments"
  },
  {
    "documentType": "Project Management Plan / Project Plan",
    "practiceAreas": [
      "PLAN"
    ],
    "keywords": [
      "Scope",
      "3. Organization Responsibilities",
      "4. Project Organization Structure:",
      "schedule",
      "effort",
      "resources",
      "milestones",
      "risks",
      "communication",
      "approvals",
      "objectives",
      "deliverables",
      "estimation",
      "effort sizing",
      "project organization",
      "roles & responsibilities",
      "milestones"
    ],
    "expectedEvidence": "Approved/baselined project plan and revisions"
  },
  {
    "documentType": "Estimation Sheet",
    "practiceAreas": [
      "PLAN",
      "EST"
    ],
    "keywords": [
      "Size",
      "effort",
      "duration",
      "resources",
      "assumptions",
      "estimation method",
      "BOM Size Guidelines",
      "Weightage",
      "Estimated Effort(Hours)"
    ],
    "expectedEvidence": "Calculation sheet; estimation approval; historical data if used"
  },
  {
    "documentType": "Project Schedule",
    "practiceAreas": [
      "PLAN"
    ],
    "keywords": [
      "Tasks",
      "PHASES & MILESTONES",
      "dependencies",
      "owners",
      "baseline vs actual dates"
    ],
    "expectedEvidence": "MS Project/Jira/Azure DevOps schedule"
  },
  {
    "documentType": "BRD / SRS / Requirements Specification/RFP",
    "practiceAreas": [
      "RDM"
    ],
    "keywords": [
      "Requirement IDs",
      "functional/non-functional requirements",
      "acceptance criteria",
      "priority",
      "version",
      "approval"
    ],
    "expectedEvidence": "Approved requirement baseline"
  },
  {
    "documentType": "Requirements Traceability Matrix (RTM)",
    "practiceAreas": [
      "RDM",
      "VV"
    ],
    "keywords": [
      "Requirement-to-design/code/test/defect traceability",
      "coverage",
      "status(requirement ID",
      "design reference",
      "code module",
      "test case ID",
      "bidirectional traceability",
      "coverage",
      "status",
      "source)"
    ],
    "expectedEvidence": "Updated RTM with end-to-end links"
  },
  {
    "documentType": "Risk Register",
    "practiceAreas": [
      "RSK"
    ],
    "keywords": [
      "Risk ID",
      "probability",
      "impact",
      "rating",
      "owner",
      "mitigation",
      "contingency",
      "status",
      "risk category",
      "risk appetite",
      "probability scale",
      "impact scale",
      "threshold",
      "mitigation strategy",
      "risk owner",
      "review frequency"
    ],
    "expectedEvidence": "Current risk register and review history"
  },
  {
    "documentType": "Project Status / Weekly Reports/PSR",
    "practiceAreas": [
      "MPM",
      "PLAN"
    ],
    "keywords": [
      "Planned vs actual effort/schedule",
      "milestones",
      "risks",
      "issues",
      "dependencies",
      "actions",
      "Activities Planned for the Reporting Period:",
      "Activities Planned for the next Reporting Period:",
      "Status of Actionable of the previous review meeting (Non WBS Activity):",
      "Issues for Management:"
    ],
    "expectedEvidence": "Periodic status reports"
  },
  {
    "documentType": "Project Metrics / Dashboard",
    "practiceAreas": [
      "MPM"
    ],
    "keywords": [
      "Effort",
      "schedule",
      "defects",
      "productivity",
      "quality",
      "trends",
      "thresholds",
      "corrective actions"
    ],
    "expectedEvidence": "Metrics dashboard/reports"
  },
  {
    "documentType": "Issue Log",
    "practiceAreas": [
      "MPM"
    ],
    "keywords": [
      "Issue/action",
      "owner",
      "priority",
      "due date",
      "status",
      "closure evidence",
      "incident ID",
      "reported date",
      "severity",
      "impacted service",
      "status",
      "downtime",
      "resolution",
      "closure date"
    ],
    "expectedEvidence": "Updated issue/action log"
  },
  {
    "documentType": "Configuration Management Plan",
    "practiceAreas": [
      "CM"
    ],
    "keywords": [
      "Configuration items",
      "baselines",
      "repository",
      "versioning",
      "access",
      "change control"
    ],
    "expectedEvidence": "Approved CM plan"
  },
  {
    "documentType": "Git / Repository Evidence",
    "practiceAreas": [
      "CM"
    ],
    "keywords": [
      "Branches",
      "commits",
      "tags/releases",
      "access",
      "version history",
      "baselines"
    ],
    "expectedEvidence": "Repository history/screenshots/export"
  },
  {
    "documentType": "Change Request / Change Log",
    "practiceAreas": [
      "RDM",
      "CM",
      "MPM"
    ],
    "keywords": [
      "Change ID",
      "reason",
      "impact analysis",
      "approval",
      "implementation",
      "testing",
      "closure"
    ],
    "expectedEvidence": "Approved CRs and change log"
  },
  {
    "documentType": "HLD – High Level Design",
    "practiceAreas": [
      "TS",
      "RDM"
    ],
    "keywords": [
      "Architecture",
      "components",
      "interfaces",
      "data flow",
      "technologies",
      "requirement mapping"
    ],
    "expectedEvidence": "Approved HLD and review evidence"
  },
  {
    "documentType": "LLD – Low Level Design",
    "practiceAreas": [
      "TS"
    ],
    "keywords": [
      "Modules",
      "classes/components",
      "DB design",
      "APIs",
      "logic",
      "error handling"
    ],
    "expectedEvidence": "Approved LLD and review evidence"
  },
  {
    "documentType": "Source Code",
    "practiceAreas": [
      "TS",
      "CM"
    ],
    "keywords": [
      "Coding standards",
      "version control",
      "requirement linkage",
      "branches/merges",
      "static analysis"
    ],
    "expectedEvidence": "Repository/source code evidence"
  },
  {
    "documentType": "Code Review / Peer Review",
    "practiceAreas": [
      "VV",
      "TS"
    ],
    "keywords": [
      "Reviewer",
      "date",
      "scope",
      "comments",
      "defects",
      "corrective action",
      "closure"
    ],
    "expectedEvidence": "PR/MR/code review records"
  },
  {
    "documentType": "Test Plan",
    "practiceAreas": [
      "VV"
    ],
    "keywords": [
      "Scope",
      "strategy",
      "levels",
      "entry/exit criteria",
      "environment",
      "responsibilities"
    ],
    "expectedEvidence": "Approved test plan"
  },
  {
    "documentType": "Test Cases / Scenarios",
    "practiceAreas": [
      "VV"
    ],
    "keywords": [
      "Test ID",
      "requirement mapping",
      "steps",
      "expected/actual result",
      "status",
      "tester",
      "date"
    ],
    "expectedEvidence": "Test case repository"
  },
  {
    "documentType": "Test Execution Evidence",
    "practiceAreas": [
      "VV"
    ],
    "keywords": [
      "Execution results",
      "pass/fail",
      "logs/screenshots",
      "failed test handling",
      "retesting",
      "regression"
    ],
    "expectedEvidence": "Execution reports/logs"
  },
  {
    "documentType": "Defect Log",
    "practiceAreas": [
      "VV",
      "MPM"
    ],
    "keywords": [
      "Defect ID",
      "severity",
      "priority",
      "environment",
      "owner",
      "status",
      "resolution",
      "retest",
      "closure"
    ],
    "expectedEvidence": "Defect tracker/export"
  },
  {
    "documentType": "UAT / Customer Acceptance",
    "practiceAreas": [
      "VV"
    ],
    "keywords": [
      "UAT scenarios",
      "acceptance criteria",
      "results",
      "open issues",
      "customer approval"
    ],
    "expectedEvidence": "UAT results and sign-off"
  },
  {
    "documentType": "QA / Process Audit Reports",
    "practiceAreas": [
      "PQA"
    ],
    "keywords": [
      "Audit plan",
      "criteria",
      "findings",
      "NCs",
      "corrective actions",
      "closure"
    ],
    "expectedEvidence": "QA/process audit reports"
  },
  {
    "documentType": "Review Records",
    "practiceAreas": [
      "PQA",
      "VV"
    ],
    "keywords": [
      "Requirement/design/code/test reviews",
      "participants",
      "findings",
      "actions",
      "closure"
    ],
    "expectedEvidence": "Review minutes/checklists"
  },
  {
    "documentType": "Measurement Plan",
    "practiceAreas": [
      "MPM"
    ],
    "keywords": [
      "Measurement objectives",
      "metrics",
      "frequency",
      "source",
      "owner",
      "calculation",
      "targets"
    ],
    "expectedEvidence": "Approved measurement plan"
  },
  {
    "documentType": "Metrics / Measurement Repository",
    "practiceAreas": [
      "MPM"
    ],
    "keywords": [
      "Effort",
      "schedule",
      "defects",
      "productivity",
      "quality",
      "baseline/target",
      "actual",
      "trends"
    ],
    "expectedEvidence": "Measurement records/dashboard"
  },
  {
    "documentType": "Supplier / Vendor Documents (if applicable)",
    "practiceAreas": [
      "SUP"
    ],
    "keywords": [
      "Scope",
      "deliverables",
      "SLA",
      "acceptance criteria",
      "responsibilities",
      "monitoring"
    ],
    "expectedEvidence": "Supplier agreement/review records or N/A justification"
  },
  {
    "documentType": "Training / Skill Matrix",
    "practiceAreas": [
      "OT"
    ],
    "keywords": [
      "Required skills",
      "available skills",
      "gaps",
      "training needs",
      "completion"
    ],
    "expectedEvidence": "Skill matrix/training records"
  },
  {
    "documentType": "Resource / Staffing Plan",
    "practiceAreas": [
      "OT",
      "PLAN"
    ],
    "keywords": [
      "Required resources",
      "assigned resources",
      "roles",
      "allocation",
      "changes"
    ],
    "expectedEvidence": "Resource plan"
  },
  {
    "documentType": "Release Plan",
    "practiceAreas": [
      "CM",
      "PLAN",
      "VV"
    ],
    "keywords": [
      "Release scope/version",
      "date",
      "components",
      "dependencies",
      "rollback",
      "approval"
    ],
    "expectedEvidence": "Approved release plan"
  },
  {
    "documentType": "Deployment / Release Evidence",
    "practiceAreas": [
      "CM",
      "VV"
    ],
    "keywords": [
      "Deployment logs",
      "version/tag",
      "environment",
      "approval",
      "result",
      "rollback"
    ],
    "expectedEvidence": "Deployment logs/release records"
  },
  {
    "documentType": "Lessons Learned",
    "practiceAreas": [
      "MPM",
      "PQA",
      "PLAN"
    ],
    "keywords": [
      "What went well/wrong",
      "root causes",
      "improvements",
      "actions",
      "reuse",
      "LL ID",
      "LL Area",
      "I/R/O ID",
      "LL Details"
    ],
    "expectedEvidence": "Lessons learned record/action tracking"
  }
];
