// AUTO-GENERATED by scripts/buildRuleChecklist.mjs from
// "rule checklist/CMMI_v3_Rule_Based_Audit_Checklist_v2.xlsx" (sheet: Sheet2).
// Do not edit manually — re-run the script to regenerate.

export const SHEET2_DATA = [
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Process Quality Assurance (PQA)",
    "relatedDocument": "Quality Assurance Plan / QA Strategy/OEG/SEPG PLAN",
    "keywords": [
      "QA plan",
      "sepg plan",
      "objective evaluation",
      "audit schedule",
      "QA roles",
      "non-compliance handling",
      "Operational Excellence Group",
      "Process Assessments",
      "Scope",
      "Roles and Responsibilities:  Quality Objectives",
      "Quality Assurance Activities",
      "Process Development and Improvement Activities"
    ],
    "exampleEvidence": "Project QA Plan (QAP-APOLLO-v1.2) defining fortnightly process audits, sampling of 20% work products and escalation of open non-compliances to the PMO."
  },
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Process Quality Assurance (PQA)",
    "relatedDocument": "Process / Compliance Audit Report/ Internal, External  Audit Report",
    "keywords": [
      "Audit type",
      "audit finding",
      "observation",
      "non-conformance (NC)",
      "audit criteria",
      "auditee",
      "audit date",
      "corrective action",
      "Auditor name",
      "Auditee name",
      "audit date/Bussiness Objective/ORG KPI"
    ],
    "exampleEvidence": "Internal Process Audit Report QA-2026-14 for Project Apollo recording 3 minor NCs against the configuration control process."
  },
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Process Quality Assurance (PQA)",
    "relatedDocument": "Non-Conformance Report (NCR) / CAPA Register",
    "keywords": [
      "NCR ID",
      "root cause",
      "corrective action",
      "preventive action",
      "responsible owner",
      "target closure date",
      "verification",
      "status"
    ],
    "exampleEvidence": "NCR-118: 'Peer review records missing for Sprint 6' - corrective action verified and closed on 15-Mar-2026."
  },
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Process Quality Assurance (PQA)",
    "relatedDocument": "Quality Audit Checklist",
    "keywords": [
      "checklist item",
      "evidence reference",
      "compliant / non-compliant",
      "not applicable",
      "auditor remarks",
      "process ID",
      "practice area",
      "verification method"
    ],
    "exampleEvidence": "PQA audit checklist confirming that approved estimation records exist for all work packages of Release 4.0."
  },
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Process Quality Assurance (PQA)",
    "relatedDocument": "Process Improvement log",
    "keywords": [],
    "exampleEvidence": ""
  },
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Process Quality Assurance (PQA)",
    "relatedDocument": "Internal Audit Schedule",
    "keywords": [
      "Project Name",
      "Scope",
      "Auditees",
      "Auditors",
      "Date of Audit",
      "day",
      "time"
    ],
    "exampleEvidence": ""
  },
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Process Quality Assurance (PQA)",
    "relatedDocument": "Internal Audit Analysis/ Internal Audit Suimmary Report",
    "keywords": [
      "Department",
      "KPI",
      "Formula",
      "Frequency",
      "Target",
      "Audit Analysis",
      "Audit Planned Audit",
      "Conducted",
      "Effectiveness"
    ],
    "exampleEvidence": ""
  },
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Process Quality Assurance (PQA)",
    "relatedDocument": "Management review meeting",
    "keywords": [
      "MINUTES OF MEETING",
      "Meeting title: Management Review Meeting (MRM)",
      "Meeting objective",
      "Points discussed / Action Item",
      "Name of Member with Function / Designation"
    ],
    "exampleEvidence": ""
  },
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Process Quality Assurance (PQA)",
    "relatedDocument": "Risk and opportunities",
    "keywords": [],
    "exampleEvidence": ""
  },
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Process Quality Assurance (PQA)",
    "relatedDocument": "Internal/External Audit plan, Annual Internal Audit plan",
    "keywords": [],
    "exampleEvidence": ""
  },
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Process Quality Assurance (PQA)",
    "relatedDocument": "Quality Status / QA Metrics Report/ Bussiness Objectives",
    "keywords": [
      "quality objective",
      "NC trend",
      "audit closure rate",
      "defect density",
      "review effectiveness",
      "escalation summary",
      "period"
    ],
    "exampleEvidence": "Monthly QA dashboard for Mar-2026 showing NC closure at 92% against a target of 95%."
  },
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Requirements Development and Management (RDM)",
    "relatedDocument": "Statement of Work (SOW) / Contract Scope Document",
    "keywords": [
      "scope of work",
      "deliverables",
      "acceptance criteria",
      "assumptions",
      "exclusions",
      "milestones",
      "customer obligations",
      "change control clause"
    ],
    "exampleEvidence": "SOW for the ERP Implementation listing five module deliverables with module-wise acceptance criteria and a 10-day acceptance window."
  },
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Requirements Development and Management (RDM)",
    "relatedDocument": "Business Requirements Document (BRD) / Requirements Gathering Document",
    "keywords": [
      "stakeholder",
      "business need",
      "elicitation workshop",
      "as-is process",
      "to-be process",
      "interview notes",
      "assumption",
      "sign-off"
    ],
    "exampleEvidence": "Requirements elicitation workshop record dated 04-Feb-2026 with signed stakeholder attendance and agreed to-be process flows."
  },
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Requirements Development and Management (RDM)",
    "relatedDocument": "Software / System Requirements Specification (SRS)",
    "keywords": [
      "functional requirement",
      "non-functional requirement",
      "requirement ID",
      "use case",
      "actor",
      "business rule",
      "constraint",
      "interface requirement"
    ],
    "exampleEvidence": "SRS v2.1, requirement FR-021: 'The system shall lock a user account after five consecutive failed login attempts.'"
  },
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Requirements Development and Management (RDM)",
    "relatedDocument": "Requirements Traceability Matrix (RTM)",
    "keywords": [
      "requirement ID",
      "design reference",
      "code module",
      "test case ID",
      "bidirectional traceability",
      "coverage",
      "status",
      "source"
    ],
    "exampleEvidence": "RTM sheet mapping FR-021 -> DES-14 -> TC-088, evidencing 100% forward and backward requirement coverage."
  },
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Requirements Development and Management (RDM)",
    "relatedDocument": "Requirements Change Request & Impact Analysis / Sign-off Record",
    "keywords": [
      "change request ID",
      "impact analysis",
      "affected requirements",
      "effort estimate",
      "CCB approval",
      "baseline version",
      "requirement sign-off",
      "disposition"
    ],
    "exampleEvidence": "CR-07 approved by the CCB on 20-Apr-2026 after a 12 person-day impact assessment against requirements baseline v1.3."
  },
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Peer Reviews (PR)",
    "relatedDocument": "Peer Review Plan / Review Schedule",
    "keywords": [
      "work product",
      "review type",
      "reviewer",
      "moderator",
      "planned date",
      "entry criteria",
      "exit criteria",
      "planned effort"
    ],
    "exampleEvidence": "Peer Review Plan for Release 4.0 scheduling design inspections for all high-complexity modules before coding starts."
  },
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Peer Reviews (PR)",
    "relatedDocument": "Peer Review Checklist (Code / Design / Document)",
    "keywords": [
      "checklist item",
      "coding standard",
      "completeness",
      "correctness",
      "consistency",
      "severity",
      "comment",
      "standard reference"
    ],
    "exampleEvidence": "Code review checklist CR-CHK-03 verifying exception handling and naming conventions for the Payments module."
  },
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Peer Reviews (PR)",
    "relatedDocument": "Peer Review Record / Review Log",
    "keywords": [
      "defect ID",
      "defect type",
      "severity",
      "reviewer",
      "preparation time",
      "review effort",
      "disposition",
      "rework status",
      "closure date"
    ],
    "exampleEvidence": "Peer Review Log PRL-22 recording 14 review comments on the Login module, all closed and re-verified by the moderator."
  },
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Peer Reviews (PR)",
    "relatedDocument": "Inspection / Walkthrough Report (Formal Review)",
    "keywords": [
      "moderator",
      "author",
      "inspection meeting",
      "participants",
      "lines of code reviewed",
      "defect density",
      "decision",
      "re-inspection"
    ],
    "exampleEvidence": "Design inspection report for HLD v1.0 covering 42 pages, resulting in a 're-inspect after rework' decision."
  },
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Peer Reviews (PR)",
    "relatedDocument": "Peer Review Defect Analysis / Effectiveness Report",
    "keywords": [
      "review effectiveness",
      "defect removal efficiency",
      "defects per KLOC",
      "phase containment",
      "review coverage",
      "trend"
    ],
    "exampleEvidence": "Quarterly review effectiveness report showing 68% of defects removed before testing against an organizational baseline of 60%."
  },
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Verification and Validation (VV)",
    "relatedDocument": "Test Plan / Test Strategy",
    "keywords": [
      "test scope",
      "test levels",
      "entry criteria",
      "exit criteria",
      "test environment",
      "test data",
      "test tools",
      "regression approach",
      "risk"
    ],
    "exampleEvidence": "System Test Plan v1.4 defining an exit criterion of zero open Severity-1 and Severity-2 defects."
  },
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Verification and Validation (VV)",
    "relatedDocument": "Test Cases / Test Scripts",
    "keywords": [
      "test case ID",
      "precondition",
      "test step",
      "test data",
      "expected result",
      "actual result",
      "pass / fail",
      "linked requirement ID"
    ],
    "exampleEvidence": "Test case TC-088 verifying account lockout after five failed logins, traced to requirement FR-021."
  },
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Verification and Validation (VV)",
    "relatedDocument": "Test Execution Log / Test Summary Report",
    "keywords": [
      "executed",
      "passed",
      "failed",
      "blocked",
      "build version",
      "test cycle",
      "pass percentage",
      "defect count",
      "exit criteria met"
    ],
    "exampleEvidence": "Test Summary Report for Build 4.0.7: 512 cases executed, 496 passed, 16 failed, cycle-2 pass rate 96.9%."
  },
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Verification and Validation (VV)",
    "relatedDocument": "Defect Log / Bug Report",
    "keywords": [
      "defect ID",
      "severity",
      "priority",
      "status",
      "steps to reproduce",
      "environment",
      "root cause",
      "reopened",
      "closed date"
    ],
    "exampleEvidence": "Defect DEF-2291 (Severity-1) on OTP validation failure, reopened once and closed in Build 4.0.9."
  },
  {
    "domain": "Doing - Ensuring Quality",
    "practiceArea": "Verification and Validation (VV)",
    "relatedDocument": "UAT / Validation Report & Acceptance Sign-off",
    "keywords": [
      "user acceptance testing",
      "business scenario",
      "acceptance criteria",
      "UAT sign-off",
      "stakeholder approval",
      "go-live readiness",
      "deviation accepted"
    ],
    "exampleEvidence": "UAT sign-off note signed by the Business Head on 28-May-2026 accepting Release 4.0 with two deferred cosmetic defects."
  },
  {
    "domain": "Doing - Engineering and Developing Products",
    "practiceArea": "Technical Solution (TS)",
    "relatedDocument": "High-Level Design (HLD) / Architecture Document",
    "keywords": [
      "architecture",
      "component",
      "module",
      "data flow",
      "interface",
      "deployment diagram",
      "technology stack",
      "scalability",
      "non-functional requirement"
    ],
    "exampleEvidence": "HLD v1.0 describing a three-tier architecture with a load-balanced application layer sized for 5,000 concurrent users."
  },
  {
    "domain": "Doing - Engineering and Developing Products",
    "practiceArea": "Technical Solution (TS)",
    "relatedDocument": "Low-Level Design (LLD) / Detailed Design Document",
    "keywords": [
      "class diagram",
      "sequence diagram",
      "pseudo code",
      "database schema",
      "API specification",
      "error handling",
      "module design",
      "field validation"
    ],
    "exampleEvidence": "LLD for the Payments module detailing 12 API methods, table structures and error codes."
  },
  {
    "domain": "Doing - Engineering and Developing Products",
    "practiceArea": "Technical Solution (TS)",
    "relatedDocument": "Solution Alternatives / Design Rationale Note",
    "keywords": [
      "alternative solution",
      "evaluation criteria",
      "trade-off",
      "selected approach",
      "rationale",
      "build vs buy",
      "feasibility",
      "constraint"
    ],
    "exampleEvidence": "Design rationale note comparing REST and gRPC for the internal service layer, selecting REST for team familiarity."
  },
  {
    "domain": "Doing - Engineering and Developing Products",
    "practiceArea": "Technical Solution (TS)",
    "relatedDocument": "Coding Standards & Development Guidelines",
    "keywords": [
      "naming convention",
      "code structure",
      "commenting standard",
      "secure coding",
      "static analysis",
      "exception handling",
      "version header"
    ],
    "exampleEvidence": "Organizational Java Coding Standard v3.0 mandating SonarQube static analysis with zero blocker issues before check-in."
  },
  {
    "domain": "Doing - Engineering and Developing Products",
    "practiceArea": "Technical Solution (TS)",
    "relatedDocument": "User Manual / Installation & Operations Guide",
    "keywords": [
      "installation steps",
      "prerequisites",
      "configuration",
      "user guide",
      "screen navigation",
      "troubleshooting",
      "release notes",
      "support contact"
    ],
    "exampleEvidence": "End-User Manual v2.0 for the Self-Service Portal, issued along with Release 4.0."
  },
  {
    "domain": "Doing - Engineering and Developing Products",
    "practiceArea": "Product Integration (PI)",
    "relatedDocument": "Integration Plan / Integration Strategy",
    "keywords": [
      "integration sequence",
      "build order",
      "dependency",
      "integration environment",
      "interface list",
      "readiness criteria",
      "integration approach"
    ],
    "exampleEvidence": "Integration Plan defining bottom-up integration of the Payments, Billing and Notification services in three stages."
  },
  {
    "domain": "Doing - Engineering and Developing Products",
    "practiceArea": "Product Integration (PI)",
    "relatedDocument": "Interface Control Document (ICD) / API Specification",
    "keywords": [
      "interface ID",
      "API contract",
      "request",
      "response",
      "data format",
      "protocol",
      "message schema",
      "error code",
      "authentication"
    ],
    "exampleEvidence": "ICD-05 specifying the JSON payload and error codes for the Payment Gateway interface."
  },
  {
    "domain": "Doing - Engineering and Developing Products",
    "practiceArea": "Product Integration (PI)",
    "relatedDocument": "Build & Release Notes / Deployment Document",
    "keywords": [
      "build number",
      "release version",
      "deployed components",
      "deployment checklist",
      "rollback plan",
      "environment",
      "deployment date"
    ],
    "exampleEvidence": "Release Note for Build 4.0.9 listing 14 deployed components and a documented rollback procedure."
  },
  {
    "domain": "Doing - Engineering and Developing Products",
    "practiceArea": "Product Integration (PI)",
    "relatedDocument": "Integration Test Report",
    "keywords": [
      "integration test case",
      "interface defect",
      "end-to-end flow",
      "stub",
      "driver",
      "environment",
      "pass / fail",
      "retest"
    ],
    "exampleEvidence": "Integration Test Report confirming successful end-to-end order-to-payment flow across all three services."
  },
  {
    "domain": "Doing - Engineering and Developing Products",
    "practiceArea": "Product Integration (PI)",
    "relatedDocument": "Delivery Note / Product Handover Record",
    "keywords": [
      "delivery note",
      "packaged components",
      "checksum",
      "media",
      "delivery date",
      "acceptance",
      "handover sign-off",
      "installation confirmation"
    ],
    "exampleEvidence": "Delivery Note DN-31 handing over the Release 4.0 package with MD5 checksums, acknowledged by the customer IT team."
  },
  {
    "domain": "Doing - Delivering and Managing Services",
    "practiceArea": "Service Delivery Management (SDM)",
    "relatedDocument": "Service Level Agreement (SLA)",
    "keywords": [
      "service level",
      "response time",
      "resolution time",
      "availability",
      "uptime",
      "service hours",
      "penalty clause",
      "priority definition"
    ],
    "exampleEvidence": "SLA committing 99.5% monthly availability and a 4-hour resolution time for Priority-1 incidents."
  },
  {
    "domain": "Doing - Delivering and Managing Services",
    "practiceArea": "Service Delivery Management (SDM)",
    "relatedDocument": "Service Delivery Plan / Operations Manual",
    "keywords": [
      "service scope",
      "delivery approach",
      "roles and responsibilities",
      "shift roster",
      "request type",
      "standard operating procedure",
      "handover"
    ],
    "exampleEvidence": "Service Delivery Plan for the AMS engagement defining a 24x7 three-shift support model."
  },
  {
    "domain": "Doing - Delivering and Managing Services",
    "practiceArea": "Service Delivery Management (SDM)",
    "relatedDocument": "Service Request / Ticket Log",
    "keywords": [
      "ticket ID",
      "request type",
      "priority",
      "logged date",
      "assigned to",
      "SLA breach",
      "closure date",
      "resolution notes"
    ],
    "exampleEvidence": "Service desk extract for Apr-2026 showing 428 tickets closed with 6 SLA breaches."
  },
  {
    "domain": "Doing - Delivering and Managing Services",
    "practiceArea": "Service Delivery Management (SDM)",
    "relatedDocument": "Service Review / Performance Report",
    "keywords": [
      "SLA compliance",
      "MTTR",
      "backlog",
      "ageing",
      "service metrics",
      "escalation",
      "period",
      "corrective action"
    ],
    "exampleEvidence": "Monthly Service Review Report for Apr-2026 recording 98.6% SLA compliance and an MTTR of 3.2 hours."
  },
  {
    "domain": "Doing - Delivering and Managing Services",
    "practiceArea": "Service Delivery Management (SDM)",
    "relatedDocument": "Customer Satisfaction (CSAT) Survey / Feedback Record",
    "keywords": [
      "customer feedback",
      "satisfaction score",
      "survey response",
      "complaint",
      "appreciation",
      "improvement action",
      "rating scale"
    ],
    "exampleEvidence": "CSAT survey for Q1 FY26 with an average score of 4.3 out of 5 and two agreed improvement actions."
  },
  {
    "domain": "Doing - Delivering and Managing Services",
    "practiceArea": "Strategic Service Management (STSM)",
    "relatedDocument": "Standard Service Description / Service Catalogue",
    "keywords": [
      "standard service",
      "service description",
      "service owner",
      "service level",
      "target customer",
      "service category",
      "offering"
    ],
    "exampleEvidence": "Service Catalogue listing 'Application Managed Services - Gold' with defined coverage hours and response commitments."
  },
  {
    "domain": "Doing - Delivering and Managing Services",
    "practiceArea": "Strategic Service Management (STSM)",
    "relatedDocument": "Market & Customer Needs Analysis Report",
    "keywords": [
      "market analysis",
      "customer need",
      "demand trend",
      "competitor",
      "service gap",
      "segment",
      "opportunity"
    ],
    "exampleEvidence": "Market analysis identifying rising demand for cloud migration support, leading to a new service offering."
  },
  {
    "domain": "Doing - Delivering and Managing Services",
    "practiceArea": "Strategic Service Management (STSM)",
    "relatedDocument": "Service Strategy / Service Roadmap Document",
    "keywords": [
      "strategic objective",
      "service portfolio",
      "roadmap",
      "business case",
      "investment",
      "target market",
      "timeline"
    ],
    "exampleEvidence": "Service Roadmap FY26-FY28 approved by the leadership team, adding two managed-cloud offerings."
  },
  {
    "domain": "Doing - Delivering and Managing Services",
    "practiceArea": "Strategic Service Management (STSM)",
    "relatedDocument": "Service Portfolio Review Minutes",
    "keywords": [
      "portfolio review",
      "new service",
      "enhance",
      "retire",
      "management decision",
      "review date",
      "attendees",
      "action item"
    ],
    "exampleEvidence": "Portfolio review minutes dated 12-Jan-2026 approving retirement of the legacy on-premise hosting service."
  },
  {
    "domain": "Doing - Delivering and Managing Services",
    "practiceArea": "Incident Resolution and Prevention (IRP)",
    "relatedDocument": "Incident Management Process / Plan",
    "keywords": [
      "incident category",
      "priority matrix",
      "escalation matrix",
      "workaround",
      "resolution SLA",
      "notification",
      "ownership"
    ],
    "exampleEvidence": "Incident Management Process v2.0 with a four-level priority matrix and a defined escalation ladder."
  },
  {
    "domain": "Doing - Delivering and Managing Services",
    "practiceArea": "Incident Resolution and Prevention (IRP)",
    "relatedDocument": "Incident Log / Incident Register",
    "keywords": [
      "incident ID",
      "reported date",
      "severity",
      "impacted service",
      "status",
      "downtime",
      "resolution",
      "closure date"
    ],
    "exampleEvidence": "Incident register entry INC-4471: 45-minute payment gateway outage on 08-Mar-2026, resolved and closed."
  },
  {
    "domain": "Doing - Delivering and Managing Services",
    "practiceArea": "Incident Resolution and Prevention (IRP)",
    "relatedDocument": "Root Cause Analysis (RCA) Report",
    "keywords": [
      "root cause",
      "5 Whys",
      "fishbone diagram",
      "contributing factor",
      "corrective action",
      "preventive action",
      "timeline of events"
    ],
    "exampleEvidence": "RCA for INC-4471 identifying an expired TLS certificate as the root cause, with automated expiry alerts added."
  },
  {
    "domain": "Doing - Delivering and Managing Services",
    "practiceArea": "Incident Resolution and Prevention (IRP)",
    "relatedDocument": "Known Error / Problem Record",
    "keywords": [
      "problem ID",
      "known error",
      "workaround",
      "recurrence",
      "permanent fix",
      "underlying cause",
      "linked incidents"
    ],
    "exampleEvidence": "Problem record PRB-77 documenting a recurring session timeout with a temporary workaround pending a vendor patch."
  },
  {
    "domain": "Doing - Delivering and Managing Services",
    "practiceArea": "Incident Resolution and Prevention (IRP)",
    "relatedDocument": "Incident Trend & Prevention Report",
    "keywords": [
      "trend analysis",
      "recurring incident",
      "Pareto",
      "incident reduction",
      "preventive measure",
      "category-wise analysis"
    ],
    "exampleEvidence": "Quarterly incident trend report showing a 30% reduction in database-related incidents after index tuning."
  },
  {
    "domain": "Doing - Delivering and Managing Services",
    "practiceArea": "Continuity (CONT)",
    "relatedDocument": "Business Continuity Plan (BCP)",
    "keywords": [
      "critical function",
      "RTO",
      "RPO",
      "continuity strategy",
      "alternate site",
      "activation criteria",
      "emergency contact",
      "crisis team"
    ],
    "exampleEvidence": "BCP v3.0 defining a 4-hour RTO and 1-hour RPO for the core banking application."
  },
  {
    "domain": "Doing - Delivering and Managing Services",
    "practiceArea": "Continuity (CONT)",
    "relatedDocument": "Disaster Recovery (DR) Plan",
    "keywords": [
      "DR site",
      "failover",
      "failback",
      "backup",
      "restoration procedure",
      "replication",
      "recovery sequence",
      "DR contact list"
    ],
    "exampleEvidence": "DR Plan documenting warm-standby failover to the Hyderabad data centre with step-by-step recovery instructions."
  },
  {
    "domain": "Doing - Delivering and Managing Services",
    "practiceArea": "Continuity (CONT)",
    "relatedDocument": "Business Impact Analysis (BIA)",
    "keywords": [
      "essential function",
      "impact rating",
      "dependency",
      "maximum tolerable downtime",
      "financial impact",
      "criticality",
      "resource requirement"
    ],
    "exampleEvidence": "BIA rating the payments service as 'Critical' with a maximum tolerable downtime of 4 hours."
  },
  {
    "domain": "Doing - Delivering and Managing Services",
    "practiceArea": "Continuity (CONT)",
    "relatedDocument": "BCP / DR Drill & Test Report",
    "keywords": [
      "drill date",
      "test scenario",
      "participants",
      "observation",
      "RTO achieved",
      "gap",
      "corrective action",
      "next drill"
    ],
    "exampleEvidence": "DR drill report dated 18-Feb-2026 achieving failover in 3 hours 10 minutes against a 4-hour RTO."
  },
  {
    "domain": "Doing - Delivering and Managing Services",
    "practiceArea": "Continuity (CONT)",
    "relatedDocument": "Backup & Restoration Records",
    "keywords": [
      "backup schedule",
      "backup type",
      "full backup",
      "incremental",
      "retention period",
      "restoration test",
      "backup log",
      "storage location"
    ],
    "exampleEvidence": "Backup log for Mar-2026 with a successful quarterly restoration test evidenced on 25-Mar-2026."
  },
  {
    "domain": "Doing - Selecting and Managing Suppliers",
    "practiceArea": "Supplier Agreement Management (SAM)",
    "relatedDocument": "Supplier Agreement / Contract / Purchase Order",
    "keywords": [
      "contract terms",
      "deliverables",
      "payment milestone",
      "penalty clause",
      "NDA",
      "SLA",
      "validity period",
      "termination clause"
    ],
    "exampleEvidence": "Purchase Order PO-2026-088 with a testing vendor, including milestone-linked payments and a confidentiality clause."
  },
  {
    "domain": "Doing - Selecting and Managing Suppliers",
    "practiceArea": "Supplier Agreement Management (SAM)",
    "relatedDocument": "Supplier Deliverable Acceptance Record",
    "keywords": [
      "acceptance criteria",
      "deliverable review",
      "acceptance sign-off",
      "rejection",
      "rework",
      "delivery date",
      "verification"
    ],
    "exampleEvidence": "Acceptance record for the vendor-supplied test automation suite, signed after successful verification on 30-Apr-2026."
  },
  {
    "domain": "Doing - Selecting and Managing Suppliers",
    "practiceArea": "Supplier Agreement Management (SAM)",
    "relatedDocument": "Supplier Performance Evaluation / Scorecard",
    "keywords": [
      "supplier rating",
      "on-time delivery",
      "quality score",
      "responsiveness",
      "evaluation period",
      "weightage",
      "corrective action"
    ],
    "exampleEvidence": "Half-yearly vendor scorecard rating the vendor 4.1 of 5, with an action to improve documentation quality."
  },
  {
    "domain": "Doing - Selecting and Managing Suppliers",
    "practiceArea": "Supplier Agreement Management (SAM)",
    "relatedDocument": "Supplier Review Meeting Minutes",
    "keywords": [
      "review meeting",
      "attendees",
      "agenda",
      "open issue",
      "action item",
      "escalation",
      "commitment",
      "next review date"
    ],
    "exampleEvidence": "Monthly vendor governance MoM dated 05-May-2026 recording three open actions with owners and due dates."
  },
  {
    "domain": "Doing - Selecting and Managing Suppliers",
    "practiceArea": "Supplier Agreement Management (SAM)",
    "relatedDocument": "Supplier Invoice & Payment Verification Record",
    "keywords": [
      "invoice number",
      "milestone completion",
      "verification",
      "approval",
      "payment release",
      "hold",
      "deduction"
    ],
    "exampleEvidence": "Invoice INV-556 verified against Milestone-2 completion and released for payment after QA confirmation."
  },
  {
    "domain": "Doing - Selecting and Managing Suppliers",
    "practiceArea": "Supplier Source Selection (SSS)",
    "relatedDocument": "Request for Proposal (RFP) / RFQ / Tender Document",
    "keywords": [
      "RFP",
      "scope of supply",
      "submission deadline",
      "eligibility criteria",
      "evaluation criteria",
      "technical bid",
      "commercial bid",
      "terms"
    ],
    "exampleEvidence": "RFP-2026-03 for infrastructure monitoring tools, issued to five empanelled vendors with a 21-day response window."
  },
  {
    "domain": "Doing - Selecting and Managing Suppliers",
    "practiceArea": "Supplier Source Selection (SSS)",
    "relatedDocument": "Supplier Evaluation Criteria & Comparison Matrix",
    "keywords": [
      "evaluation criteria",
      "weightage",
      "technical score",
      "commercial score",
      "ranking",
      "shortlist",
      "scoring method"
    ],
    "exampleEvidence": "Vendor comparison matrix scoring three bidders on a 70:30 technical-to-commercial weightage."
  },
  {
    "domain": "Doing - Selecting and Managing Suppliers",
    "practiceArea": "Supplier Source Selection (SSS)",
    "relatedDocument": "Due Diligence / Vendor Capability Assessment Report",
    "keywords": [
      "financial stability",
      "capability assessment",
      "reference check",
      "certification",
      "compliance verification",
      "site visit",
      "risk"
    ],
    "exampleEvidence": "Due diligence report confirming the vendor's ISO 9001 certification and two positive client references."
  },
  {
    "domain": "Doing - Selecting and Managing Suppliers",
    "practiceArea": "Supplier Source Selection (SSS)",
    "relatedDocument": "Bid Evaluation / Selection Justification Report",
    "keywords": [
      "bid comparison",
      "negotiation",
      "lowest bidder",
      "selection rationale",
      "award decision",
      "approval authority",
      "recommendation"
    ],
    "exampleEvidence": "Selection note recommending Vendor-B on the basis of the highest composite score, approved by the Procurement Head."
  },
  {
    "domain": "Doing - Selecting and Managing Suppliers",
    "practiceArea": "Supplier Source Selection (SSS)",
    "relatedDocument": "Approved Supplier List / Vendor Empanelment Record",
    "keywords": [
      "approved vendor",
      "empanelment",
      "vendor category",
      "registration date",
      "validity",
      "de-listing",
      "vendor code"
    ],
    "exampleEvidence": "Approved Supplier List FY26 listing 18 empanelled vendors with category and empanelment validity dates."
  },
  {
    "domain": "Managing - Planning and Managing Work",
    "practiceArea": "Estimating (EST)",
    "relatedDocument": "Effort Estimation Sheet / Estimation Document",
    "keywords": [
      "effort estimate",
      "person-hours",
      "person-days",
      "work breakdown structure",
      "task-wise estimate",
      "assumption",
      "buffer",
      "contingency",
      "productivity"
    ],
    "exampleEvidence": "Estimation sheet for Release 4.0 estimating 1,840 person-hours across 62 WBS tasks with a 10% contingency."
  },
  {
    "domain": "Managing - Planning and Managing Work",
    "practiceArea": "Estimating (EST)",
    "relatedDocument": "Estimation Model / Estimation Guideline",
    "keywords": [
      "estimation technique",
      "function point",
      "story point",
      "three-point estimation",
      "COCOMO",
      "historical data",
      "calibration",
      "productivity factor"
    ],
    "exampleEvidence": "Organizational Estimation Guideline v2.0 prescribing function point analysis for fixed-price bids."
  },
  {
    "domain": "Managing - Planning and Managing Work",
    "practiceArea": "Estimating (EST)",
    "relatedDocument": "Size Estimation / Function Point Count Sheet",
    "keywords": [
      "size measure",
      "function point count",
      "lines of code",
      "story points",
      "complexity factor",
      "adjustment factor",
      "count date",
      "counting rules"
    ],
    "exampleEvidence": "Function point count sheet computing 412 adjusted function points for the Billing module."
  },
  {
    "domain": "Managing - Planning and Managing Work",
    "practiceArea": "Estimating (EST)",
    "relatedDocument": "Cost & Resource Estimation Sheet",
    "keywords": [
      "cost estimate",
      "rate card",
      "resource loading",
      "skill mix",
      "infrastructure cost",
      "licence cost",
      "contingency",
      "total budget"
    ],
    "exampleEvidence": "Cost estimate of INR 92.4 lakh derived from the effort estimate and the approved FY26 rate card."
  },
  {
    "domain": "Managing - Planning and Managing Work",
    "practiceArea": "Estimating (EST)",
    "relatedDocument": "Estimation Review & Approval Record",
    "keywords": [
      "estimation review",
      "reviewer",
      "approval",
      "revised estimate",
      "variance",
      "basis of estimate",
      "sign-off"
    ],
    "exampleEvidence": "Estimation review record showing a 7% upward revision after the delivery manager's review on 12-Jan-2026."
  },
  {
    "domain": "Managing - Planning and Managing Work",
    "practiceArea": "Planning (PLAN)",
    "relatedDocument": "Project Management Plan (PMP) / Project Plan",
    "keywords": [
      "objective",
      "scope",
      "work breakdown structure",
      "milestone",
      "deliverable",
      "roles and responsibilities",
      "dependency",
      "assumption",
      "approval"
    ],
    "exampleEvidence": "PMP-APOLLO v1.0 approved on 05-Jan-2026, covering scope, schedule, quality, risk and communication approaches."
  },
  {
    "domain": "Managing - Planning and Managing Work",
    "practiceArea": "Planning (PLAN)",
    "relatedDocument": "Project Schedule / Gantt Chart (MPP)",
    "keywords": [
      "task",
      "duration",
      "start date",
      "finish date",
      "predecessor",
      "critical path",
      "baseline",
      "milestone",
      "percentage complete",
      "resource assignment"
    ],
    "exampleEvidence": "Baselined MS Project schedule with 62 tasks, 5 milestones and a critical path running through the integration phase."
  },
  {
    "domain": "Managing - Planning and Managing Work",
    "practiceArea": "Planning (PLAN)",
    "relatedDocument": "Resource / Staffing Plan",
    "keywords": [
      "resource allocation",
      "role",
      "skill requirement",
      "ramp-up",
      "ramp-down",
      "availability",
      "effort distribution",
      "onboarding date"
    ],
    "exampleEvidence": "Staffing plan showing a peak of 14 resources in Mar-2026 with skill-wise ramp-up dates."
  },
  {
    "domain": "Managing - Planning and Managing Work",
    "practiceArea": "Planning (PLAN)",
    "relatedDocument": "Communication & Stakeholder Management Plan",
    "keywords": [
      "stakeholder",
      "communication frequency",
      "reporting channel",
      "escalation matrix",
      "RACI",
      "meeting cadence",
      "distribution list"
    ],
    "exampleEvidence": "Communication plan defining weekly status reports to the customer and a three-level escalation matrix."
  },
  {
    "domain": "Managing - Planning and Managing Work",
    "practiceArea": "Planning (PLAN)",
    "relatedDocument": "Plan Review, Commitment & Baseline Record",
    "keywords": [
      "plan review",
      "stakeholder commitment",
      "sign-off",
      "baseline version",
      "revision history",
      "approval date",
      "agreed plan"
    ],
    "exampleEvidence": "Kick-off MoM recording formal commitment of all stakeholders to PMP v1.0 and its baselined schedule."
  },
  {
    "domain": "Managing - Planning and Managing Work",
    "practiceArea": "Monitoring and Control (MC)",
    "relatedDocument": "Project Status Report (Weekly / Monthly)",
    "keywords": [
      "reporting period",
      "planned versus actual",
      "percentage complete",
      "milestone status",
      "accomplishment",
      "planned next",
      "open issue",
      "risk summary"
    ],
    "exampleEvidence": "Weekly Status Report WSR-18 reporting 74% completion against a plan of 78%, with recovery actions listed."
  },
  {
    "domain": "Managing - Planning and Managing Work",
    "practiceArea": "Monitoring and Control (MC)",
    "relatedDocument": "Project / Milestone Review Minutes (MoM)",
    "keywords": [
      "review date",
      "attendees",
      "agenda",
      "decision",
      "action item",
      "owner",
      "target date",
      "status of previous actions"
    ],
    "exampleEvidence": "Milestone-2 review MoM dated 14-Apr-2026 approving progression to the integration phase with two conditions."
  },
  {
    "domain": "Managing - Planning and Managing Work",
    "practiceArea": "Monitoring and Control (MC)",
    "relatedDocument": "Issue Log / Action Item Tracker",
    "keywords": [
      "issue ID",
      "description",
      "raised date",
      "owner",
      "priority",
      "due date",
      "status",
      "resolution",
      "ageing"
    ],
    "exampleEvidence": "Issue log entry ISS-24: 'UAT environment unavailable', escalated to IT and closed within 3 days."
  },
  {
    "domain": "Managing - Planning and Managing Work",
    "practiceArea": "Monitoring and Control (MC)",
    "relatedDocument": "Effort & Schedule Variance Report",
    "keywords": [
      "effort variance",
      "schedule variance",
      "SPI",
      "CPI",
      "earned value",
      "threshold",
      "deviation",
      "planned versus actual effort"
    ],
    "exampleEvidence": "Variance report for Apr-2026 showing an effort variance of +8.5%, exceeding the 5% control threshold."
  },
  {
    "domain": "Managing - Planning and Managing Work",
    "practiceArea": "Monitoring and Control (MC)",
    "relatedDocument": "Corrective Action Log / Deviation Record",
    "keywords": [
      "deviation",
      "corrective action",
      "root cause",
      "responsible person",
      "target date",
      "closure",
      "effectiveness verification"
    ],
    "exampleEvidence": "Corrective action CA-09 adding two developers to recover a 6-day schedule slippage, verified as effective in May-2026."
  },
  {
    "domain": "Managing - Managing Business Resilience",
    "practiceArea": "Risk and Opportunity Management (RSK)",
    "relatedDocument": "Risk Management Plan",
    "keywords": [
      "risk category",
      "risk appetite",
      "probability scale",
      "impact scale",
      "threshold",
      "mitigation strategy",
      "risk owner",
      "review frequency"
    ],
    "exampleEvidence": "Risk Management Plan defining a 5x5 probability-impact matrix and monthly risk review cadence."
  },
  {
    "domain": "Managing - Managing Business Resilience",
    "practiceArea": "Risk and Opportunity Management (RSK)",
    "relatedDocument": "Risk Register / Risk Log",
    "keywords": [
      "risk ID",
      "risk description",
      "probability",
      "impact",
      "risk exposure",
      "mitigation plan",
      "contingency plan",
      "trigger",
      "owner",
      "status"
    ],
    "exampleEvidence": "Risk register entry RSK-06: 'Key resource attrition' - exposure High, mitigated through cross-training two backups."
  },
  {
    "domain": "Managing - Managing Business Resilience",
    "practiceArea": "Risk and Opportunity Management (RSK)",
    "relatedDocument": "Opportunity Register / Opportunity Analysis",
    "keywords": [
      "opportunity ID",
      "expected benefit",
      "likelihood",
      "exploitation plan",
      "owner",
      "realised benefit",
      "status"
    ],
    "exampleEvidence": "Opportunity OPP-02: reuse of an existing payment component, saving an estimated 120 person-hours."
  },
  {
    "domain": "Managing - Managing Business Resilience",
    "practiceArea": "Risk and Opportunity Management (RSK)",
    "relatedDocument": "Risk Review / Reassessment Record",
    "keywords": [
      "risk review",
      "revised rating",
      "new risk",
      "closed risk",
      "residual risk",
      "review date",
      "participants"
    ],
    "exampleEvidence": "Monthly risk review of May-2026 closing two risks and adding one new vendor-dependency risk."
  },
  {
    "domain": "Managing - Managing Business Resilience",
    "practiceArea": "Risk and Opportunity Management (RSK)",
    "relatedDocument": "Risk Escalation / Materialised Risk Record",
    "keywords": [
      "escalated risk",
      "risk materialised",
      "converted to issue",
      "management attention",
      "contingency invoked",
      "impact realised"
    ],
    "exampleEvidence": "Escalation note recording that risk RSK-06 materialised in Apr-2026 and the contingency plan was invoked."
  },
  {
    "domain": "Managing - Managing the Workforce",
    "practiceArea": "Organizational Training (OT)",
    "relatedDocument": "Training Needs Analysis (TNA) / Skill Gap Assessment",
    "keywords": [
      "skill gap",
      "competency",
      "required skill level",
      "current skill level",
      "training need",
      "role-wise requirement",
      "assessment date"
    ],
    "exampleEvidence": "TNA for FY26 identifying cloud security and automation testing as the top two organization-wide skill gaps."
  },
  {
    "domain": "Managing - Managing the Workforce",
    "practiceArea": "Organizational Training (OT)",
    "relatedDocument": "Organizational / Annual Training Plan & Calendar",
    "keywords": [
      "training calendar",
      "training program",
      "target audience",
      "trainer",
      "mode of training",
      "duration",
      "budget",
      "scheduled date"
    ],
    "exampleEvidence": "FY26 Training Calendar scheduling 24 programs, including four mandatory process and security trainings."
  },
  {
    "domain": "Managing - Managing the Workforce",
    "practiceArea": "Organizational Training (OT)",
    "relatedDocument": "Training Attendance & Completion Records",
    "keywords": [
      "attendance sheet",
      "participant name",
      "employee ID",
      "trainer",
      "training date",
      "duration",
      "completion status",
      "certificate"
    ],
    "exampleEvidence": "Attendance sheet for the 'Secure Coding' session dated 10-Feb-2026 with 28 participants and issued certificates."
  },
  {
    "domain": "Managing - Managing the Workforce",
    "practiceArea": "Organizational Training (OT)",
    "relatedDocument": "Training Feedback & Effectiveness Evaluation",
    "keywords": [
      "feedback score",
      "trainer rating",
      "content relevance",
      "post-training assessment",
      "pre-test",
      "post-test",
      "effectiveness",
      "on-the-job application"
    ],
    "exampleEvidence": "Training effectiveness evaluation showing an average post-test score of 82% and a 4.4 of 5 feedback rating."
  },
  {
    "domain": "Managing - Managing the Workforce",
    "practiceArea": "Organizational Training (OT)",
    "relatedDocument": "Competency / Skill Matrix & Induction Records",
    "keywords": [
      "skill matrix",
      "proficiency level",
      "certification",
      "induction",
      "onboarding checklist",
      "role readiness",
      "appraisal linkage"
    ],
    "exampleEvidence": "Team skill matrix rating each member on eight technologies, used to plan the Q2 training nominations."
  },
  {
    "domain": "Enabling - Supporting Implementation",
    "practiceArea": "Configuration Management (CM)",
    "relatedDocument": "Configuration Management Plan",
    "keywords": [
      "configuration item",
      "CI naming convention",
      "baseline",
      "repository",
      "access rights",
      "branching strategy",
      "backup",
      "CM audit",
      "CM roles"
    ],
    "exampleEvidence": "CM Plan v1.1 defining the Git branching strategy, CI naming convention and monthly configuration audits."
  },
  {
    "domain": "Enabling - Supporting Implementation",
    "practiceArea": "Configuration Management (CM)",
    "relatedDocument": "Configuration Item (CI) List / CI Register",
    "keywords": [
      "CI ID",
      "CI name",
      "version",
      "type",
      "storage location",
      "owner",
      "baseline reference",
      "status"
    ],
    "exampleEvidence": "CI register listing 214 controlled items including source code, design documents, test cases and scripts."
  },
  {
    "domain": "Enabling - Supporting Implementation",
    "practiceArea": "Configuration Management (CM)",
    "relatedDocument": "Version Control / Check-in-Check-out Log",
    "keywords": [
      "version history",
      "check-in",
      "check-out",
      "commit ID",
      "revision",
      "branch",
      "merge",
      "tag",
      "author",
      "timestamp"
    ],
    "exampleEvidence": "Git commit history for the Payments module showing tagged release v4.0.9 with author and timestamp details."
  },
  {
    "domain": "Enabling - Supporting Implementation",
    "practiceArea": "Configuration Management (CM)",
    "relatedDocument": "Baseline Record / Release Baseline Report",
    "keywords": [
      "baseline ID",
      "baseline date",
      "baseline contents",
      "frozen version",
      "approval",
      "release label",
      "change since last baseline"
    ],
    "exampleEvidence": "Baseline record BL-04 freezing the Release 4.0 code, design and test artefacts on 20-May-2026."
  },
  {
    "domain": "Enabling - Supporting Implementation",
    "practiceArea": "Configuration Management (CM)",
    "relatedDocument": "Change Request Log / CCB Minutes",
    "keywords": [
      "change request ID",
      "requested by",
      "impact analysis",
      "CCB decision",
      "approved",
      "rejected",
      "implemented version",
      "closure"
    ],
    "exampleEvidence": "CCB minutes dated 22-Apr-2026 approving 4 of 6 change requests, with implementation targeted for Build 4.0.9."
  },
  {
    "domain": "Enabling - Supporting Implementation",
    "practiceArea": "Configuration Management (CM)",
    "relatedDocument": "Configuration Audit Report (FCA / PCA)",
    "keywords": [
      "functional configuration audit",
      "physical configuration audit",
      "discrepancy",
      "CI verification",
      "completeness",
      "audit date",
      "corrective action"
    ],
    "exampleEvidence": "Configuration audit report of 25-May-2026 verifying that all baselined CIs matched the release manifest."
  },
  {
    "domain": "Enabling - Supporting Implementation",
    "practiceArea": "Decision Analysis and Resolution (DAR)",
    "relatedDocument": "Decision Analysis Record / DAR Report",
    "keywords": [
      "decision statement",
      "decision criteria",
      "weightage",
      "alternatives considered",
      "evaluation method",
      "selected alternative",
      "rationale",
      "approval"
    ],
    "exampleEvidence": "DAR-03 selecting a cloud provider using five weighted criteria, with the decision approved by the CTO."
  },
  {
    "domain": "Enabling - Supporting Implementation",
    "practiceArea": "Decision Analysis and Resolution (DAR)",
    "relatedDocument": "Alternative Evaluation / Trade-off Matrix",
    "keywords": [
      "criteria",
      "weight",
      "score",
      "weighted score",
      "comparison",
      "advantages",
      "limitations",
      "ranking"
    ],
    "exampleEvidence": "Evaluation matrix comparing three automation tools on cost, coverage, skill availability and support."
  },
  {
    "domain": "Enabling - Supporting Implementation",
    "practiceArea": "Decision Analysis and Resolution (DAR)",
    "relatedDocument": "Tool / Technology Selection Report",
    "keywords": [
      "tool evaluation",
      "proof of concept",
      "feasibility",
      "licensing cost",
      "integration effort",
      "recommendation",
      "trial result"
    ],
    "exampleEvidence": "Tool selection report recommending Selenium after a two-week proof of concept on the regression suite."
  },
  {
    "domain": "Enabling - Supporting Implementation",
    "practiceArea": "Decision Analysis and Resolution (DAR)",
    "relatedDocument": "Make-or-Buy / Cost-Benefit Analysis",
    "keywords": [
      "build versus buy",
      "cost-benefit",
      "total cost of ownership",
      "payback",
      "risk",
      "assumption",
      "recommendation"
    ],
    "exampleEvidence": "Make-or-buy analysis showing a 14-month payback for purchasing the reporting engine instead of building it."
  },
  {
    "domain": "Enabling - Supporting Implementation",
    "practiceArea": "Decision Analysis and Resolution (DAR)",
    "relatedDocument": "Decision Approval / Management Review Minutes",
    "keywords": [
      "approval authority",
      "decision log",
      "decision date",
      "stakeholders informed",
      "communication",
      "rationale recorded"
    ],
    "exampleEvidence": "Management review MoM recording formal approval of DAR-03 and its communication to all project teams."
  },
  {
    "domain": "Enabling - Supporting Implementation",
    "practiceArea": "Causal Analysis and Resolution (CAR)",
    "relatedDocument": "Causal Analysis Report",
    "keywords": [
      "cause category",
      "defect category",
      "Pareto analysis",
      "fishbone diagram",
      "5 Whys",
      "common cause",
      "special cause",
      "selected outcome"
    ],
    "exampleEvidence": "Causal analysis of Release 4.0 defects showing that 62% originated from incomplete requirements."
  },
  {
    "domain": "Enabling - Supporting Implementation",
    "practiceArea": "Causal Analysis and Resolution (CAR)",
    "relatedDocument": "Root Cause Analysis (RCA) Record",
    "keywords": [
      "problem statement",
      "root cause",
      "contributing factor",
      "evidence",
      "corrective action",
      "verification",
      "closure date"
    ],
    "exampleEvidence": "RCA record for repeated UAT failures, tracing the cause to a missing requirements review checkpoint."
  },
  {
    "domain": "Enabling - Supporting Implementation",
    "practiceArea": "Causal Analysis and Resolution (CAR)",
    "relatedDocument": "Defect Prevention Plan / Action Log",
    "keywords": [
      "preventive action",
      "defect prevention",
      "implementation owner",
      "target date",
      "pilot",
      "effectiveness measure",
      "status"
    ],
    "exampleEvidence": "Defect prevention action introducing a mandatory requirements checklist, reducing requirement defects by 35%."
  },
  {
    "domain": "Enabling - Supporting Implementation",
    "practiceArea": "Causal Analysis and Resolution (CAR)",
    "relatedDocument": "Lessons Learned / Best Practices Repository",
    "keywords": [
      "lessons learned",
      "what went well",
      "what did not go well",
      "improvement suggestion",
      "reusable practice",
      "applicability"
    ],
    "exampleEvidence": "Lessons learned register from Project Apollo, with three practices uploaded to the organizational repository."
  },
  {
    "domain": "Enabling - Supporting Implementation",
    "practiceArea": "Causal Analysis and Resolution (CAR)",
    "relatedDocument": "Post-Implementation / Project Closure Analysis Report",
    "keywords": [
      "post-mortem",
      "project closure",
      "recurrence",
      "benefit realised",
      "improvement action",
      "performance against goals"
    ],
    "exampleEvidence": "Project closure report for Apollo comparing final effort and defect performance against the committed goals."
  },
  {
    "domain": "Enabling - Managing Safety",
    "practiceArea": "Enabling Safety (ESAF)",
    "relatedDocument": "Safety Management Plan / Safety Policy",
    "keywords": [
      "safety objective",
      "safety requirement",
      "safety roles",
      "regulatory compliance",
      "hazard management",
      "safety culture",
      "approval"
    ],
    "exampleEvidence": "Safety Management Plan for the medical device software project, aligned to IEC 62304 requirements."
  },
  {
    "domain": "Enabling - Managing Safety",
    "practiceArea": "Enabling Safety (ESAF)",
    "relatedDocument": "Hazard Analysis / Safety Risk Assessment",
    "keywords": [
      "hazard ID",
      "hazard description",
      "severity",
      "likelihood",
      "safety risk",
      "mitigation",
      "residual risk",
      "safety-critical function"
    ],
    "exampleEvidence": "Hazard analysis identifying incorrect dosage display as a critical hazard, mitigated by dual-range validation."
  },
  {
    "domain": "Enabling - Managing Safety",
    "practiceArea": "Enabling Safety (ESAF)",
    "relatedDocument": "Safety Requirements & Compliance Matrix",
    "keywords": [
      "safety standard",
      "regulation",
      "clause",
      "compliance status",
      "evidence reference",
      "verification method",
      "gap"
    ],
    "exampleEvidence": "Compliance matrix mapping each IEC 62304 clause to the corresponding project evidence."
  },
  {
    "domain": "Enabling - Managing Safety",
    "practiceArea": "Enabling Safety (ESAF)",
    "relatedDocument": "Safety Incident / Near-Miss Report",
    "keywords": [
      "incident date",
      "description",
      "injury",
      "near miss",
      "investigation",
      "root cause",
      "corrective action",
      "reported by"
    ],
    "exampleEvidence": "Near-miss report for a workplace electrical hazard, closed after rewiring and re-inspection."
  },
  {
    "domain": "Enabling - Managing Safety",
    "practiceArea": "Enabling Safety (ESAF)",
    "relatedDocument": "Safety Training & Drill Records",
    "keywords": [
      "safety training",
      "fire drill",
      "evacuation",
      "attendance",
      "awareness session",
      "emergency response",
      "drill observation"
    ],
    "exampleEvidence": "Fire evacuation drill record of 09-Mar-2026 with 312 participants and an evacuation time of 4 minutes."
  },
  {
    "domain": "Enabling - Managing Security",
    "practiceArea": "Enabling Security (ESEC)",
    "relatedDocument": "Information Security Policy / ISMS Manual",
    "keywords": [
      "information security policy",
      "data classification",
      "acceptable use",
      "confidentiality",
      "password policy",
      "ISMS scope",
      "policy review"
    ],
    "exampleEvidence": "Information Security Policy v4.0 approved by the CISO, covering data classification and acceptable use."
  },
  {
    "domain": "Enabling - Managing Security",
    "practiceArea": "Enabling Security (ESEC)",
    "relatedDocument": "Security Requirements / Secure Coding Guidelines",
    "keywords": [
      "authentication",
      "authorization",
      "encryption",
      "input validation",
      "OWASP Top 10",
      "session management",
      "secure design",
      "logging"
    ],
    "exampleEvidence": "Secure coding guideline mandating parameterised queries and OWASP Top 10 verification before release."
  },
  {
    "domain": "Enabling - Managing Security",
    "practiceArea": "Enabling Security (ESEC)",
    "relatedDocument": "Access Control / User Access Review Record",
    "keywords": [
      "user ID",
      "role-based access",
      "access request",
      "approval",
      "privilege",
      "revocation",
      "periodic access review",
      "segregation of duties"
    ],
    "exampleEvidence": "Quarterly access review for Q1 FY26 revoking 12 dormant accounts and 3 excess privileges."
  },
  {
    "domain": "Enabling - Managing Security",
    "practiceArea": "Enabling Security (ESEC)",
    "relatedDocument": "Security Awareness Training & Acknowledgement Records",
    "keywords": [
      "security awareness",
      "phishing simulation",
      "training attendance",
      "policy acknowledgement",
      "NDA",
      "confidentiality undertaking"
    ],
    "exampleEvidence": "Security awareness training record with 98% completion and signed policy acknowledgements on file."
  },
  {
    "domain": "Enabling - Managing Security",
    "practiceArea": "Enabling Security (ESEC)",
    "relatedDocument": "Security Audit / Compliance Report (ISO 27001)",
    "keywords": [
      "audit finding",
      "control",
      "Annexure A",
      "non-conformity",
      "evidence",
      "corrective action",
      "surveillance audit",
      "certification"
    ],
    "exampleEvidence": "ISO 27001 surveillance audit report of Feb-2026 with two minor non-conformities, both closed within 30 days."
  },
  {
    "domain": "Enabling - Managing Security",
    "practiceArea": "Managing Security Threats and Vulnerabilities (MST)",
    "relatedDocument": "Threat & Vulnerability Assessment Report",
    "keywords": [
      "threat",
      "vulnerability",
      "asset",
      "CVE",
      "CVSS score",
      "severity",
      "exposure",
      "likelihood",
      "countermeasure"
    ],
    "exampleEvidence": "Vulnerability assessment report listing 4 high and 11 medium findings across the production environment."
  },
  {
    "domain": "Enabling - Managing Security",
    "practiceArea": "Managing Security Threats and Vulnerabilities (MST)",
    "relatedDocument": "VAPT / Penetration Testing Report",
    "keywords": [
      "penetration test",
      "scope",
      "exploit",
      "proof of concept",
      "finding",
      "remediation",
      "retest",
      "residual risk"
    ],
    "exampleEvidence": "VAPT report dated 15-Apr-2026 with all high-severity findings remediated and verified in the retest."
  },
  {
    "domain": "Enabling - Managing Security",
    "practiceArea": "Managing Security Threats and Vulnerabilities (MST)",
    "relatedDocument": "Patch Management / Remediation Tracker",
    "keywords": [
      "patch",
      "remediation",
      "due date",
      "risk rating",
      "closure status",
      "exception approval",
      "patch cycle",
      "verification"
    ],
    "exampleEvidence": "Patch tracker showing 100% of critical patches applied within the 15-day defined SLA."
  },
  {
    "domain": "Enabling - Managing Security",
    "practiceArea": "Managing Security Threats and Vulnerabilities (MST)",
    "relatedDocument": "Security Incident Report",
    "keywords": [
      "breach",
      "unauthorised access",
      "detection",
      "containment",
      "eradication",
      "forensic analysis",
      "notification",
      "lessons learned"
    ],
    "exampleEvidence": "Security incident report for a phishing attempt detected on 02-Mar-2026, contained with no data loss."
  },
  {
    "domain": "Enabling - Managing Security",
    "practiceArea": "Managing Security Threats and Vulnerabilities (MST)",
    "relatedDocument": "Security Risk Treatment Plan",
    "keywords": [
      "risk treatment",
      "mitigate",
      "accept",
      "transfer",
      "avoid",
      "control implementation",
      "residual risk",
      "owner",
      "target date"
    ],
    "exampleEvidence": "Risk treatment plan accepting one low residual risk with documented CISO approval and a review date."
  },
  {
    "domain": "Improving - Building and Sustaining Capability",
    "practiceArea": "Governance (GOV)",
    "relatedDocument": "Quality / Organizational Policy Document",
    "keywords": [
      "policy statement",
      "management commitment",
      "scope",
      "objective",
      "approval authority",
      "effective date",
      "review cycle"
    ],
    "exampleEvidence": "Quality Policy v2.0 signed by the Managing Director and displayed across all delivery locations."
  },
  {
    "domain": "Improving - Building and Sustaining Capability",
    "practiceArea": "Governance (GOV)",
    "relatedDocument": "Management Review Meeting (MRM) Minutes",
    "keywords": [
      "management review",
      "performance against objectives",
      "resource commitment",
      "decision",
      "action item",
      "escalation",
      "review period"
    ],
    "exampleEvidence": "MRM minutes of 30-Apr-2026 approving additional budget for the process improvement programme."
  },
  {
    "domain": "Improving - Building and Sustaining Capability",
    "practiceArea": "Governance (GOV)",
    "relatedDocument": "Organization Structure & Roles / Responsibility Matrix",
    "keywords": [
      "organization chart",
      "role",
      "responsibility",
      "authority",
      "reporting line",
      "RACI",
      "delegation",
      "function"
    ],
    "exampleEvidence": "Organization chart and RACI matrix defining accountability for QA, CM and delivery functions."
  },
  {
    "domain": "Improving - Building and Sustaining Capability",
    "practiceArea": "Governance (GOV)",
    "relatedDocument": "Business & Quality Objectives Document",
    "keywords": [
      "strategic objective",
      "measurable goal",
      "target value",
      "KPI",
      "alignment",
      "review frequency",
      "achievement status"
    ],
    "exampleEvidence": "FY26 Quality Objectives document setting a target of 15% reduction in post-release defects."
  },
  {
    "domain": "Improving - Building and Sustaining Capability",
    "practiceArea": "Governance (GOV)",
    "relatedDocument": "Steering Committee / Governance Charter",
    "keywords": [
      "steering committee",
      "charter",
      "mandate",
      "membership",
      "meeting frequency",
      "escalation",
      "sponsorship",
      "decision rights"
    ],
    "exampleEvidence": "Governance charter constituting a monthly steering committee chaired by the Delivery Head."
  },
  {
    "domain": "Improving - Building and Sustaining Capability",
    "practiceArea": "Implementation Infrastructure (II)",
    "relatedDocument": "Process Deployment / Rollout Plan",
    "keywords": [
      "deployment",
      "rollout",
      "pilot",
      "phased implementation",
      "adoption",
      "transition",
      "communication",
      "deployment owner"
    ],
    "exampleEvidence": "Deployment plan rolling out the revised estimation process to all projects over two quarters."
  },
  {
    "domain": "Improving - Building and Sustaining Capability",
    "practiceArea": "Implementation Infrastructure (II)",
    "relatedDocument": "Process Compliance / Process Usage Report",
    "keywords": [
      "process adherence",
      "usage",
      "compliance score",
      "deviation",
      "tailoring approval",
      "project-wise compliance",
      "trend"
    ],
    "exampleEvidence": "Process usage report for Q1 FY26 showing 94% adherence across 11 active projects."
  },
  {
    "domain": "Improving - Building and Sustaining Capability",
    "practiceArea": "Implementation Infrastructure (II)",
    "relatedDocument": "Tools & Infrastructure Register / IT Asset List",
    "keywords": [
      "tool",
      "licence",
      "version",
      "environment",
      "infrastructure",
      "availability",
      "support",
      "asset ID",
      "owner"
    ],
    "exampleEvidence": "Tool register listing JIRA, Git, SonarQube and Jenkins with licence counts and renewal dates."
  },
  {
    "domain": "Improving - Building and Sustaining Capability",
    "practiceArea": "Implementation Infrastructure (II)",
    "relatedDocument": "Process Tailoring Guidelines & Tailoring Records",
    "keywords": [
      "tailoring",
      "waiver",
      "deviation",
      "justification",
      "approval",
      "standard process",
      "tailoring criteria",
      "applicability"
    ],
    "exampleEvidence": "Approved tailoring record permitting a small maintenance project to combine the HLD and LLD documents."
  },
  {
    "domain": "Improving - Building and Sustaining Capability",
    "practiceArea": "Implementation Infrastructure (II)",
    "relatedDocument": "Process Training & Awareness Records",
    "keywords": [
      "process training",
      "QMS orientation",
      "awareness session",
      "attendance",
      "new process rollout",
      "refresher training"
    ],
    "exampleEvidence": "Process awareness session record dated 18-Jan-2026 covering the revised QMS with 96 attendees."
  },
  {
    "domain": "Improving - Improving Performance",
    "practiceArea": "Process Management (PCM)",
    "relatedDocument": "Process Improvement Plan / Improvement Roadmap",
    "keywords": [
      "improvement objective",
      "improvement action",
      "owner",
      "timeline",
      "milestone",
      "expected benefit",
      "priority",
      "status"
    ],
    "exampleEvidence": "Process Improvement Plan FY26 listing 9 improvement actions with owners and quarterly milestones."
  },
  {
    "domain": "Improving - Improving Performance",
    "practiceArea": "Process Management (PCM)",
    "relatedDocument": "Appraisal / Gap Analysis Report",
    "keywords": [
      "appraisal",
      "gap analysis",
      "practice area",
      "rating",
      "strength",
      "weakness",
      "finding",
      "readiness",
      "corrective action"
    ],
    "exampleEvidence": "CMMI Level-3 gap analysis report identifying gaps in MPM and CAR ahead of the benchmark appraisal."
  },
  {
    "domain": "Improving - Improving Performance",
    "practiceArea": "Process Management (PCM)",
    "relatedDocument": "Improvement Suggestion / Kaizen Register",
    "keywords": [
      "suggestion ID",
      "submitted by",
      "evaluation",
      "accepted",
      "rejected",
      "implementation status",
      "benefit",
      "reward"
    ],
    "exampleEvidence": "Improvement suggestion register with 34 suggestions received in FY26, of which 12 were implemented."
  },
  {
    "domain": "Improving - Improving Performance",
    "practiceArea": "Process Management (PCM)",
    "relatedDocument": "Improvement Pilot & Benefit Realisation Report",
    "keywords": [
      "pilot",
      "before versus after",
      "return on investment",
      "benefit realised",
      "deployment decision",
      "measurement",
      "validation"
    ],
    "exampleEvidence": "Pilot report demonstrating a 22% reduction in rework effort, leading to organization-wide deployment."
  },
  {
    "domain": "Improving - Improving Performance",
    "practiceArea": "Process Management (PCM)",
    "relatedDocument": "SEPG / EPG Meeting Minutes",
    "keywords": [
      "SEPG",
      "engineering process group",
      "agenda",
      "decision",
      "action item",
      "improvement status",
      "attendees",
      "next meeting"
    ],
    "exampleEvidence": "SEPG minutes of 20-Feb-2026 approving revisions to the peer review checklist."
  },
  {
    "domain": "Improving - Improving Performance",
    "practiceArea": "Process Asset Development (PAD)",
    "relatedDocument": "Quality Management System (QMS) Manual",
    "keywords": [
      "QMS",
      "process framework",
      "process map",
      "document hierarchy",
      "scope",
      "policy reference",
      "approval",
      "version"
    ],
    "exampleEvidence": "QMS Manual v5.0 describing the process architecture and the four-tier documentation hierarchy."
  },
  {
    "domain": "Improving - Improving Performance",
    "practiceArea": "Process Asset Development (PAD)",
    "relatedDocument": "Standard Process Definitions / SOPs",
    "keywords": [
      "purpose",
      "scope",
      "entry criteria",
      "input",
      "activity",
      "output",
      "exit criteria",
      "roles",
      "measures",
      "reference"
    ],
    "exampleEvidence": "Standard Requirements Management Process (PRO-RDM-02) defining entry criteria, activities and exit criteria."
  },
  {
    "domain": "Improving - Improving Performance",
    "practiceArea": "Process Asset Development (PAD)",
    "relatedDocument": "Templates, Checklists and Forms",
    "keywords": [
      "template ID",
      "version",
      "mandatory field",
      "usage guideline",
      "format",
      "checklist",
      "form",
      "effective date"
    ],
    "exampleEvidence": "Project Plan Template TMP-PLAN-01 v3.0 available in the process asset library for all projects."
  },
  {
    "domain": "Improving - Improving Performance",
    "practiceArea": "Process Asset Development (PAD)",
    "relatedDocument": "Process Asset Library (PAL) Index",
    "keywords": [
      "asset ID",
      "asset type",
      "version",
      "location",
      "owner",
      "effective date",
      "access",
      "retrieval",
      "reuse"
    ],
    "exampleEvidence": "PAL index listing 128 assets including processes, templates, checklists and estimation models."
  },
  {
    "domain": "Improving - Improving Performance",
    "practiceArea": "Process Asset Development (PAD)",
    "relatedDocument": "Document Change / Version History Record",
    "keywords": [
      "version",
      "revision history",
      "change description",
      "reason for change",
      "author",
      "reviewer",
      "approver",
      "effective date"
    ],
    "exampleEvidence": "Revision history of the QMS Manual showing 5 controlled revisions with approval dates and change reasons."
  },
  {
    "domain": "Improving - Improving Performance",
    "practiceArea": "Managing Performance and Measurement (MPM)",
    "relatedDocument": "Measurement Plan / Metrics Definition Document",
    "keywords": [
      "measure",
      "metric definition",
      "formula",
      "unit",
      "data source",
      "collection frequency",
      "responsibility",
      "objective alignment",
      "threshold"
    ],
    "exampleEvidence": "Measurement Plan defining 12 organizational metrics, each mapped to a business objective and a control threshold."
  },
  {
    "domain": "Improving - Improving Performance",
    "practiceArea": "Managing Performance and Measurement (MPM)",
    "relatedDocument": "Metrics Data Collection Sheet / Measurement Repository",
    "keywords": [
      "data collection",
      "actual value",
      "reporting period",
      "project ID",
      "data validation",
      "completeness",
      "data owner",
      "repository"
    ],
    "exampleEvidence": "Monthly metrics submission for Project Apollo capturing effort, schedule, defect and review data."
  },
  {
    "domain": "Improving - Improving Performance",
    "practiceArea": "Managing Performance and Measurement (MPM)",
    "relatedDocument": "Process Performance Baseline (PPB) Document",
    "keywords": [
      "baseline",
      "mean",
      "median",
      "standard deviation",
      "upper control limit",
      "lower control limit",
      "sample size",
      "historical data",
      "subgroup"
    ],
    "exampleEvidence": "PPB FY26 establishing a review effectiveness baseline of 62% with control limits of 48% and 76%."
  },
  {
    "domain": "Improving - Improving Performance",
    "practiceArea": "Managing Performance and Measurement (MPM)",
    "relatedDocument": "Process Performance Model (PPM)",
    "keywords": [
      "predictive model",
      "regression",
      "controllable factor",
      "uncontrollable factor",
      "prediction interval",
      "what-if analysis",
      "confidence level",
      "R-squared"
    ],
    "exampleEvidence": "PPM predicting post-release defect density from review effort and requirement volatility with R-squared of 0.78."
  },
  {
    "domain": "Improving - Improving Performance",
    "practiceArea": "Managing Performance and Measurement (MPM)",
    "relatedDocument": "Performance Dashboard / Metrics Analysis Report",
    "keywords": [
      "trend",
      "target versus actual",
      "control chart",
      "deviation",
      "analysis",
      "interpretation",
      "corrective action",
      "period"
    ],
    "exampleEvidence": "Organizational metrics dashboard for Q4 FY26 showing schedule variance trending down from 9% to 4%."
  }
];
